#!/bin/sh

alias ls="ls -hN --color=auto --group-directories-first" \
      ll='ls -lh' \
      la='ls -lah' \
      grep="grep --color=auto" \
      diff="diff --color=auto" \
      f="$FILE -d" \
      m="$PLAYER" \
      e="$EMAIl" \
      v="$EDITOR"

