#!/bin/sh

IMAGE="$HOME/.config/lock.*"

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#ff00ffcc'
TEXT='#ee00eeee'
WRONG='#880000bb'
VERIFYING='#bb00eeee'
FONT="Fira Code"

i3lock \
  -i $IMAGE --scale \
  --insidever-color=$CLEAR --ringver-color=$VERIFYING \
  --insidewrong-color=$CLEAR --ringwrong-color=$WRONG \
  --inside-color=$BLANK --ring-color=$DEFAULT --line-color=$BLANK --separator-color=$DEFAULT \
  --verif-color=$TEXT --wrong-color=$TEXT --time-color=$TEXT --date-color=$TEXT \
  --layout-color=$TEXT --keyhl-color=$WRONG --bshl-color=$WRONG \
  --indicator --radius 22 --ring-width 6 --verif-text="" --wrong-text="" --ind-pos x+210:y+h-80 \
  --clock --force-clock \
  --time-str="%H:%M:%S" --time-pos x+10:y+h-80  --time-align 1 \
  --date-str="%A, %Y:%m:%d" --date-pos tx:ty+15 --date-align 1 \
  --time-font="$FONT" --date-font="$FONT" --layout-font="$FONT" --verif-font="$FONT" --wrong-font="$FONT" \
  --no-modkey-text --noinput-text=''
