#!/usr/bin/env bash
if [[ $EUID -ne 0 ]]; then
  echo "Please run as root to upgrade kernel"
  exit 1
fi

set -e

MAKEOPTS="-j`nproc`"

# Save prev config
printf "Saving config has /root/kernel-`uname -r`-config\n\n"
cp /usr/src/linux/.config ~/kernel-`uname -r`-config

# List all kernels
eselect kernel list

# Read kernel
read -p "Select Kernel: " kernel
kernel=${kernel:-1}

# Set kernel
eselect kernel set $kernel

# cd to kernel folder
cd /usr/src/linux

# Menu config
make menuconfig $MAKEOPTS

# Build commands
echo "Building kernel"
make olddefconfig $MAKEOPTS
make modules_prepare $MAKEOPTS
make $MAKEOPTS
make modules_install $MAKEOPTS
make install $MAKEOPTS

# Build new genkernel
printf "Building initramfs\n\n"
genkernel --luks --lvm --kernel-config=.config --install initramfs

# Build new grub
printf "Building grub config\n\n"
grub-mkconfig -o /boot/grub/grub.cfg

# Rebuild modules
printf "Rebuild modules\n\n"
emerge -v @module-rebuild
